[pyprland]
plugins = ["expose", "monitors"]

[monitors.placement]
"Iiyama North America PL2492H 11510322E3165".leftOf = "Iiyama North America PL2492H 11510123C4540"
"LG Display 0x068D".bottomOf = "Iiyama North America PL2492H 11510123C4540"

[monitors.placement."LG Electronics LG TV SSCR2 0x01010101"]
resolution = "1920x1080"
leftOf = "LG Display 0x068D"
