version = "1.1.14"

[format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = true
dedup_inactive_fullscreen = true # false # dedup more
# window delimiter
# delim = " "
max_clients = 1 # you should not need this

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
workspace = "{id} {clients}" # {id}, {delim} and {clients} are supported
workspace_empty = "{id}" # {id}, {delim} and {clients} are supported
# client formatter
client = "{icon}"
client_active = "{icon}"

# deduplicate client formatter
client_fullscreen = "{icon}"
client_dup = "{client}"
client_dup_fullscreen = "{icon}"
client_dup_active = "{icon}"


[class]
# Add your icons mapping
# use double quote the key and the value
# take class name from 'hyprctl clients'
"DEFAULT" = "{title}"

"(?i)(SuperSlicer)" = ""
"(?i)(PrusaSlicer)" = ""
"(?i)cura" = ""

"(?i)Abiword" = ""
"(?i)libreoffice" = ""
"(?i)desktop editors" = ""
"(?i)burp-StartBurp" = ""
"(?i)Arandr" = ""
"(?i)Evince" = ""
"(?i)Evolution" = ""
"(?i)Firefox" = ""
"(?i)Firefart" = ""
"(?i)gimp" = ""
"(?i)Hopper" = ""
"(?i)Cutter" = ""
"(?i)Inkscape" = ""
"(?i)Keepassx2" = ""
"(?i)Keepassxc" = ""
"(?i)krita" = ""
"(?i)Nautilus" = ""
"(?i)pcmanfm" = ""
"(?i)Thunar" = ""
"(?i)Navigator" = ""
"(?i)OpenSCAD" = ""
"(?i)Pavucontrol" = ""
"(?i)sun-awt-X11-XFramePeer" = ""
"(?i)spotube" = ""
"(?i)QtCreator" = ""
"(?i)Designer-qt4" = ""
"(?i)quassel" = ""
"(?i)Slic3r" = ""
"(?i)Subl3" = ""
"(?i)processing-app-Base" = ""
"(?i)VirtualBox Machine" = ""
"(?i)VirtualBox" = ""
"(?i)vlc" = ""
"(?i)pantheon-music" = ""
"(?i)Lxappearance" = ""
"(?i)Wireshark-gtk" = ""
"(?i)Xfce4-terminal" = ""
"(?i)URxvt" = ""
"(?i)XTerm" = ""
"(?i)kitty" = ""
"(?i)Termite" = ""
"(?i)Zim" = ""
"(?i)wireshark-gtk" = ""
"(?i)Gitk" = ""
"(?i)rhythmbox" = ""
"(?i)Seahorse" = ""
"(?i)evience" = ""
"(?i)kicad" = ""
"(?i)VirtualBox Manager" = ""
"(?i)Virt-manager" = ""
"(?i)Virt-viewer" = ""
"(?i)Remmina" = ""
"(?i)Nm-connection-editor" = ""
"(?i)Chromium" = ""
"(?i)simple-scan" = ""
"(?i)MellowPlayer" = ""
"(?i)Brasero" = ""
"(?i)LibreCAD" = ""
"(?i)JDownloader" = ""
"(?i)jetbrains-pycharm" = ""
"(?i)TeXstudio" = ""
"(?i)Thunderbird" = ""
"(?i)Riot" = ""
"(?i)TelegramDesktop" = ""
"(?i)Blueman-manager" = ""
"(?i)Steam" = ""
"(?i)Atom" = ""
"(?i)Rocket.Chat" = ""
"(?i)Gajim" = ""
"(?i)libreoffice-calc" = ""
"(?i)libreoffice-writer" = ""
"(?i)Zotero" = ""
"(?i)Gimp" = ""
"(?i)code-oss" = ""
"(?i)factorio" = ""
"(?i)Mysql-workbench-bin" = ""
"(?i)Google-chrome" = ""
"(?i)GitKraken" = ""
"(?i)Audacity" = ""
"(?i)Code" = ""
"(?i)Code - Insiders" = ""
"(?i)firefoxdeveloperedition" = ""
"(?i)Mumble" = ""
"(?i)gnome-power-statistics" = ""

[class_active]
# DEFAULT = "{icon}"

[initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"" = "^$" # prevent displaying icon for empty class
# "(?i)fcitx" = ".*" # will match all title for fcitx
# "(?i)TestApp" = "" # will match all title for TestApp
# aProgram = "^$" # will match null title for aProgram
# "[Ss]team" = "^(Friends List.*)?$" # will match Steam friends list plus all popups (empty titles)

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"
